title: Ordinary thoughts
owner: Andrea Baldan
email:
description: Unix, Computer Science, imperative and functional programming. In an ordinary way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username:
github_username: codepr
disqus_username:
# Build settings
markdown: kramdown
theme: minima

permalink: /posts/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - .travis.yml
  - bin/*
  - circle.yml
  - README.md
  - vendor/
  - yarn.lock
excerpt_separator: <!--more-->
